version: '3'
services:
  jads_stockdashbaord:
    image: jads_stockdashbaord
    build: .
    volumes:
     - "/C/:/home/analyst/C/"
    ports:
      - "8888:8888"
      - "8788:8787"
      - "5000:5000"
      - "8081:8081" #Dash localhost ports
      - "8050:8050" #Dash localhost ports
      - "8051:8051" #Dash localhost ports
    environment:
      - JUPYTER_ENABLE_LAB=yes
    container_name: jads_stockdashbaord
    # restart: "always"


#docker-compose build
#docker-compose up